### ISSUE TITLE
Delete fixed number of chars

### ISSUE THREAD

**Issue by unclebrr** [neurobin/rnm#15]
Is there a possibility to delete fixed number of chars from beginning or from the end of filename?
I mean, if there is a special key for this, like
we have
filenamelong.ext
rnm -???? -2sfn filenamelong.ext -> lenamelong.ext
rnm -???? -2efn filenamelong.ext -> filenamelo.ext
where 
-2sfn is "delete 2 chars from filename start" and
-2efn is "delete 2 chars from filename end"
If there are no such keys pls treat this as feature request. Thank you.

**Comment by neurobin** [comment]
You can use regex:

``` sh
rnm -rs '/^.{2}//' *.ext
rnm -rs '/.{2}\./e/$/./e//' *.ext
rnm -rs '/^.{2}//;/.{2}\./e/$/./e//' *.ext
```
1. `/^.{2}//` deletes (replaces with empty string) 2 chars from beginning<br>
2. `/.{2}\./e/$/./e//` deletes (replaces with empty string) 2 chars from end preserving the extension.
3. The third one combines the above two i.e deletes from both the beginning and end.

**Comment by unclebrr** [comment]
Thank you.
I'm not so good aquainted with regex :( Still it works.
