### ISSUE TITLE
regex and [{()}]

### ISSUE THREAD

**Issue by unclebrr** [neurobin/rnm#16]
Hello, it's me again :)
Another lame question:
I need to rename a group of files within directory according to the following patterns:
filename [blablabla].ext -> filename (blablabla).ext
filename {blablabla}.ext -> filename (blablabla).ext
filename [*].ext -> filename (blablabla).ext
filename [#].ext -> filename (blablabla).ext
and possibly vice versa.
Smoked man/docs, tried any syntax but in vain...
Heed help please!

**Comment by neurobin** [comment]
In replace part of the replace string, you need to escape the spcecial chars: `[]{}()*+.?` if you mean literal meaning of those chars.

For example, `[*].ext` is `*.ext` (where `*` is literal) when it meant to be a regex, `[blablabla]` is single character (either b, l or a) when meant as regex. If you want it to be literal escape them with `\` i.e `\[blablabla\]`

**Comment by unclebrr** [comment]
Thanks for the prompt reply.
Yes I mean literal meaning. But it doesn't work. OK, let's take a concrete example:
I want to change 
01-Filename [Bonus].ext -> 01-Filename (Bonus).ext
and, second
02-Filename [*].ext -> 02-Filename (Bonus).ext
How could I do this? I get "E: Invalid replace string regex:" whatever I do.

**Comment by neurobin** [comment]
```sh
rnm -rs '/\[Bonus\]|\[*\]/(Bonus)/' *
```
this will work for both.

**Comment by unclebrr** [comment]
OK. And if there is a random literal world between those brackets - i.e. [two words] -> (two words) 
Anyway it could be a phrase or very long word... the best way for me is change the type of brackets. Can I?

**Comment by neurobin** [comment]
Well, if all you want to do is change the brackets:

```
rnm -rs '/\[/(/g;/\]/)/g' *
```

**Comment by unclebrr** [comment]
Thank you.
BTW the expression above
```sh
rnm -rs '/\[Bonus\]|\[*\]/(Bonus)/' *
```
Inserts (Bonus) after each occurence of "[" in filename. :)

**Comment by neurobin** [comment]
sorry about that, the `\[*\]` is wrong...

Use this one instead:

```sh
rnm -rs '/ \[\*\]/ (Bonus)/' *
```

**Comment by unclebrr** [comment]
Thank you!
Could you please add parts of these examples to your help page?
https://neurobin.org/docs/unix/rnm/bulk-rename-in-linux/
It is very useful for those who are lack of experience like me.

**Comment by unclebrr** [comment]
Hello Jamid and thank you for your efforts!
Just downloaded last rnm but cannot compile it.
Could you tell me where I've been wrong or compile it for 
me. The log is in attach.
Thank you!
Regards,
Mike.


---
Professional hosting for everyone - http://www.host.ru
