### ISSUE TITLE
rnm error when compiling

### ISSUE THREAD

**Issue by etanus11** [neurobin/rnm#20]
HI,
I want to compile rnm on Ubuntu 17.04, but get the following error message when running 
make
In file included from src/inout.hpp:37:0,
                 from src/func.hpp:35,
                 from src/main.cpp:33:
src/global.hpp:68:22: fatal error: jpcre2.hpp: No such file or directory
 #include <jpcre2.hpp>
the jprc2.hpp is not there.
Please advise
Renate

**Comment by neurobin** [comment]
Did you run the prepare.sh script inside the project dir? it downloads `jpcre2` and other libraries in the current directory (project directory)...

```bash
sh prepare.sh
```

**Comment by etanus11** [comment]
No, but will do it. Just ran. /configure 
Thanks 

RenateAm 10.10.2017 6:01 vorm. schrieb Md Jahidul Hamid <notifications@github.com>:

**Comment by neurobin** [comment]
Compiling from source is mentioned in [readme](https://github.com/neurobin/rnm#from-source)

**Comment by unclebrr** [comment]
When I run prepare.sh it connects to ftp.csx.cam.ac.uk hangs and gets time-out :(
