### ISSUE TITLE
Undo records might be better stored in $XDG_DATA_HOME (~/.local/share/)

### ISSUE THREAD

**Issue by newhoa** [neurobin/rnm#21]
Undo records are currently stored in ~/.cache. Many people either do not backup .cache, or clear it regularly since it is for non-essential and temporary files. Files in .cache usually regenerate themselves as needed. For log files this might be okay since they are non-critical.

Undo records are important, however, and should be stored in a directory that is persistent. Using the [freedesktop standard $XDG_DATA_HOME](https://specifications.freedesktop.org/basedir-spec/0.6/ar01s03.html), usually pointing to ~/.local/share, would be ideal.

This is just my opinion, but I think $XDG_DATA_HOME would be more appropriate.

**Comment by neurobin** [comment]
Thanks for the suggestion. I think you are right. I will try to fix it in next update.
