### ISSUE TITLE
how to rename extension

### ISSUE THREAD

**Issue by buzai** [neurobin/rnm#23]
i have a dir
a/b/c/a.class
a/c/b.class

i want rename all file 
a/b/c/a.java
a/c/b.java

**Comment by neurobin** [comment]
```
rnm -ns '/n/.java' -ss '\.class$' -dp -1 ./a
```

Explanation:
---------------

* `/n/`: file name without extension
* `-ss`: search string (regex). 
* `\.class$` searches for files with `.class` at the end of their names
* `-dp -1`: unlimited depth, go to all sub-dirs

**Comment by buzai** [comment]
@neurobin great，3q your good tool
