### ISSUE TITLE
reserved index and search string together

### ISSUE THREAD

**Issue by neurobin** [neurobin/rnm#7]
If search string is provided, reserved index reserves indexes for all files (including the files that are not complying to the search string), this is useful in some cases but seems a bit odd in my opinion. I am thinking whether to regard it as a bug or a feature.

Comments or suggestions expected...

**Comment by unclebrr** [comment]
Hello. I think that shal be feature, but documented feature :)

**Comment by neurobin** [comment]
It's a documented feature now...
